每日飲食指南手冊
https://www.hpa.gov.tw/Pages/EBook.aspx?nodeid=1208

In [14]:
import pandas as pd
import random

# Define food portions and their respective calorie values (estimated based on average serving sizes)
person_subject_scores = {
    "Alice": {"Mathematics": 85, "Physics": 90, "History": 78, "English": 88},
    "Bob": {"Mathematics": 92, "Physics": 85, "History": 80, "English": 90},
    "Charlie": {"Mathematics": 78, "Physics": 88, "History": 85, "English": 82},
    "David": {"Mathematics": 89, "Physics": 84, "History": 90, "English": 86}
}

# 計算每個人的總分
person_totals = {person: sum(subjects.values()) for person, subjects in person_subject_scores.items()}

print(person_totals)

{'Alice': 341, 'Bob': 347, 'Charlie': 333, 'David': 349}

In [16]:
person_subject_scores = {
    "Alice": {"Mathematics": 85, "Physics": 90, "History": 78, "English": 88},
    "Bob": {"Mathematics": 92, "Physics": 85, "History": 80, "English": 90},
    "Charlie": {"Mathematics": 78, "Physics": 88, "History": 85, "English": 82},
    "David": {"Mathematics": 89, "Physics": 84, "History": 90, "English": 86}
}

# Calculate the total score for each person
person_totals = {person: sum(subjects.values()) for person, subjects in person_subject_scores.items()}
person_totals

{'Alice': 341, 'Bob': 347, 'Charlie': 333, 'David': 349}

In [17]:
def generate_performance_score(person_name, subject_scores):
    performance_scores = {subject: random.randint(1, 10) * score for subject, score in subject_scores.items()}
    total_performance = sum(performance_scores.values())
    return performance_scores, total_performance

# Generate performance scores for each person
person_performance_scores = {}

In [18]:
for person, subject_scores in person_subject_scores.items():
    performance_scores, total_performance = generate_performance_score(person, subject_scores)
    person_performance_scores[person] = {
        "Performance Breakdown": performance_scores,
        "Total Performance Score": total_performance
    }

In [19]:
for person, data in person_performance_scores.items():
    print(f"{person}:")
    print(f"  Performance Breakdown: {data['Performance Breakdown']}")
    print(f"  Total Performance Score: {data['Total Performance Score']}")

Alice:
  Performance Breakdown: {'Mathematics': 255, 'Physics': 360, 'History': 312, 'English': 176}
  Total Performance Score: 1103
Bob:
  Performance Breakdown: {'Mathematics': 368, 'Physics': 170, 'History': 160, 'English': 450}
  Total Performance Score: 1148
Charlie:
  Performance Breakdown: {'Mathematics': 390, 'Physics': 264, 'History': 850, 'English': 738}
  Total Performance Score: 2242
David:
  Performance Breakdown: {'Mathematics': 534, 'Physics': 84, 'History': 540, 'English': 516}
  Total Performance Score: 1674

In [20]:
days_in_month = 30

# Initialize list to hold meal data (subject performance data)
performance_data = []

# Generate performance data for each person over 30 days
for day in range(1, days_in_month + 1):
    for person, subject_scores in person_subject_scores.items():
        # Calculate performance for each subject
        total_daily_performance = sum(subject_scores.values())
        performance_data.append([day, person, "Mathematics", subject_scores["Mathematics"], total_daily_performance])
        performance_data.append([day, person, "Physics", subject_scores["Physics"], total_daily_performance])
        performance_data.append([day, person, "History", subject_scores["History"], total_daily_performance])
        performance_data.append([day, person, "English", subject_scores["English"], total_daily_performance])
        # Add the total performance for the day (sum of all subjects)
        performance_data.append([day, person, "Total Daily Performance", "", total_daily_performance])

# Define the header for the performance data
header = ["Day", "Person", "Subject", "Subject Score", "Total Daily Performance"]

# Print results
print(header)
for row in performance_data:
    print(row)

['Day', 'Person', 'Subject', 'Subject Score', 'Total Daily Performance']
[1, 'Alice', 'Mathematics', 85, 341]
[1, 'Alice', 'Physics', 90, 341]
[1, 'Alice', 'History', 78, 341]
[1, 'Alice', 'English', 88, 341]
[1, 'Alice', 'Total Daily Performance', '', 341]
[1, 'Bob', 'Mathematics', 92, 347]
[1, 'Bob', 'Physics', 85, 347]
[1, 'Bob', 'History', 80, 347]
[1, 'Bob', 'English', 90, 347]
[1, 'Bob', 'Total Daily Performance', '', 347]
[1, 'Charlie', 'Mathematics', 78, 333]
[1, 'Charlie', 'Physics', 88, 333]
[1, 'Charlie', 'History', 85, 333]
[1, 'Charlie', 'English', 82, 333]
[1, 'Charlie', 'Total Daily Performance', '', 333]
[1, 'David', 'Mathematics', 89, 349]
[1, 'David', 'Physics', 84, 349]
[1, 'David', 'History', 90, 349]
[1, 'David', 'English', 86, 349]
[1, 'David', 'Total Daily Performance', '', 349]
[2, 'Alice', 'Mathematics', 85, 341]
[2, 'Alice', 'Physics', 90, 341]
[2, 'Alice', 'History', 78, 341]
[2, 'Alice', 'English', 88, 341]
[2, 'Alice', 'Total Daily Performance', '', 341]
[2, 'Bob', 'Mathematics', 92, 347]
[2, 'Bob', 'Physics', 85, 347]
[2, 'Bob', 'History', 80, 347]
[2, 'Bob', 'English', 90, 347]
[2, 'Bob', 'Total Daily Performance', '', 347]
[2, 'Charlie', 'Mathematics', 78, 333]
[2, 'Charlie', 'Physics', 88, 333]
[2, 'Charlie', 'History', 85, 333]
[2, 'Charlie', 'English', 82, 333]
[2, 'Charlie', 'Total Daily Performance', '', 333]
[2, 'David', 'Mathematics', 89, 349]
[2, 'David', 'Physics', 84, 349]
[2, 'David', 'History', 90, 349]
[2, 'David', 'English', 86, 349]
[2, 'David', 'Total Daily Performance', '', 349]
[3, 'Alice', 'Mathematics', 85, 341]
[3, 'Alice', 'Physics', 90, 341]
[3, 'Alice', 'History', 78, 341]
[3, 'Alice', 'English', 88, 341]
[3, 'Alice', 'Total Daily Performance', '', 341]
[3, 'Bob', 'Mathematics', 92, 347]
[3, 'Bob', 'Physics', 85, 347]
[3, 'Bob', 'History', 80, 347]
[3, 'Bob', 'English', 90, 347]
[3, 'Bob', 'Total Daily Performance', '', 347]
[3, 'Charlie', 'Mathematics', 78, 333]
[3, 'Charlie', 'Physics', 88, 333]
[3, 'Charlie', 'History', 85, 333]
[3, 'Charlie', 'English', 82, 333]
[3, 'Charlie', 'Total Daily Performance', '', 333]
[3, 'David', 'Mathematics', 89, 349]
[3, 'David', 'Physics', 84, 349]
[3, 'David', 'History', 90, 349]
[3, 'David', 'English', 86, 349]
[3, 'David', 'Total Daily Performance', '', 349]
[4, 'Alice', 'Mathematics', 85, 341]
[4, 'Alice', 'Physics', 90, 341]
[4, 'Alice', 'History', 78, 341]
[4, 'Alice', 'English', 88, 341]
[4, 'Alice', 'Total Daily Performance', '', 341]
[4, 'Bob', 'Mathematics', 92, 347]
[4, 'Bob', 'Physics', 85, 347]
[4, 'Bob', 'History', 80, 347]
[4, 'Bob', 'English', 90, 347]
[4, 'Bob', 'Total Daily Performance', '', 347]
[4, 'Charlie', 'Mathematics', 78, 333]
[4, 'Charlie', 'Physics', 88, 333]
[4, 'Charlie', 'History', 85, 333]
[4, 'Charlie', 'English', 82, 333]
[4, 'Charlie', 'Total Daily Performance', '', 333]
[4, 'David', 'Mathematics', 89, 349]
[4, 'David', 'Physics', 84, 349]
[4, 'David', 'History', 90, 349]
[4, 'David', 'English', 86, 349]
[4, 'David', 'Total Daily Performance', '', 349]
[5, 'Alice', 'Mathematics', 85, 341]
[5, 'Alice', 'Physics', 90, 341]
[5, 'Alice', 'History', 78, 341]
[5, 'Alice', 'English', 88, 341]
[5, 'Alice', 'Total Daily Performance', '', 341]
[5, 'Bob', 'Mathematics', 92, 347]
[5, 'Bob', 'Physics', 85, 347]
[5, 'Bob', 'History', 80, 347]
[5, 'Bob', 'English', 90, 347]
[5, 'Bob', 'Total Daily Performance', '', 347]
[5, 'Charlie', 'Mathematics', 78, 333]
[5, 'Charlie', 'Physics', 88, 333]
[5, 'Charlie', 'History', 85, 333]
[5, 'Charlie', 'English', 82, 333]
[5, 'Charlie', 'Total Daily Performance', '', 333]
[5, 'David', 'Mathematics', 89, 349]
[5, 'David', 'Physics', 84, 349]
[5, 'David', 'History', 90, 349]
[5, 'David', 'English', 86, 349]
[5, 'David', 'Total Daily Performance', '', 349]
[6, 'Alice', 'Mathematics', 85, 341]
[6, 'Alice', 'Physics', 90, 341]
[6, 'Alice', 'History', 78, 341]
[6, 'Alice', 'English', 88, 341]
[6, 'Alice', 'Total Daily Performance', '', 341]
[6, 'Bob', 'Mathematics', 92, 347]
[6, 'Bob', 'Physics', 85, 347]
[6, 'Bob', 'History', 80, 347]
[6, 'Bob', 'English', 90, 347]
[6, 'Bob', 'Total Daily Performance', '', 347]
[6, 'Charlie', 'Mathematics', 78, 333]
[6, 'Charlie', 'Physics', 88, 333]
[6, 'Charlie', 'History', 85, 333]
[6, 'Charlie', 'English', 82, 333]
[6, 'Charlie', 'Total Daily Performance', '', 333]
[6, 'David', 'Mathematics', 89, 349]
[6, 'David', 'Physics', 84, 349]
[6, 'David', 'History', 90, 349]
[6, 'David', 'English', 86, 349]
[6, 'David', 'Total Daily Performance', '', 349]
[7, 'Alice', 'Mathematics', 85, 341]
[7, 'Alice', 'Physics', 90, 341]
[7, 'Alice', 'History', 78, 341]
[7, 'Alice', 'English', 88, 341]
[7, 'Alice', 'Total Daily Performance', '', 341]
[7, 'Bob', 'Mathematics', 92, 347]
[7, 'Bob', 'Physics', 85, 347]
[7, 'Bob', 'History', 80, 347]
[7, 'Bob', 'English', 90, 347]
[7, 'Bob', 'Total Daily Performance', '', 347]
[7, 'Charlie', 'Mathematics', 78, 333]
[7, 'Charlie', 'Physics', 88, 333]
[7, 'Charlie', 'History', 85, 333]
[7, 'Charlie', 'English', 82, 333]
[7, 'Charlie', 'Total Daily Performance', '', 333]
[7, 'David', 'Mathematics', 89, 349]
[7, 'David', 'Physics', 84, 349]
[7, 'David', 'History', 90, 349]
[7, 'David', 'English', 86, 349]
[7, 'David', 'Total Daily Performance', '', 349]
[8, 'Alice', 'Mathematics', 85, 341]
[8, 'Alice', 'Physics', 90, 341]
[8, 'Alice', 'History', 78, 341]
[8, 'Alice', 'English', 88, 341]
[8, 'Alice', 'Total Daily Performance', '', 341]
[8, 'Bob', 'Mathematics', 92, 347]
[8, 'Bob', 'Physics', 85, 347]
[8, 'Bob', 'History', 80, 347]
[8, 'Bob', 'English', 90, 347]
[8, 'Bob', 'Total Daily Performance', '', 347]
[8, 'Charlie', 'Mathematics', 78, 333]
[8, 'Charlie', 'Physics', 88, 333]
[8, 'Charlie', 'History', 85, 333]
[8, 'Charlie', 'English', 82, 333]
[8, 'Charlie', 'Total Daily Performance', '', 333]
[8, 'David', 'Mathematics', 89, 349]
[8, 'David', 'Physics', 84, 349]
[8, 'David', 'History', 90, 349]
[8, 'David', 'English', 86, 349]
[8, 'David', 'Total Daily Performance', '', 349]
[9, 'Alice', 'Mathematics', 85, 341]
[9, 'Alice', 'Physics', 90, 341]
[9, 'Alice', 'History', 78, 341]
[9, 'Alice', 'English', 88, 341]
[9, 'Alice', 'Total Daily Performance', '', 341]
[9, 'Bob', 'Mathematics', 92, 347]
[9, 'Bob', 'Physics', 85, 347]
[9, 'Bob', 'History', 80, 347]
[9, 'Bob', 'English', 90, 347]
[9, 'Bob', 'Total Daily Performance', '', 347]
[9, 'Charlie', 'Mathematics', 78, 333]
[9, 'Charlie', 'Physics', 88, 333]
[9, 'Charlie', 'History', 85, 333]
[9, 'Charlie', 'English', 82, 333]
[9, 'Charlie', 'Total Daily Performance', '', 333]
[9, 'David', 'Mathematics', 89, 349]
[9, 'David', 'Physics', 84, 349]
[9, 'David', 'History', 90, 349]
[9, 'David', 'English', 86, 349]
[9, 'David', 'Total Daily Performance', '', 349]
[10, 'Alice', 'Mathematics', 85, 341]
[10, 'Alice', 'Physics', 90, 341]
[10, 'Alice', 'History', 78, 341]
[10, 'Alice', 'English', 88, 341]
[10, 'Alice', 'Total Daily Performance', '', 341]
[10, 'Bob', 'Mathematics', 92, 347]
[10, 'Bob', 'Physics', 85, 347]
[10, 'Bob', 'History', 80, 347]
[10, 'Bob', 'English', 90, 347]
[10, 'Bob', 'Total Daily Performance', '', 347]
[10, 'Charlie', 'Mathematics', 78, 333]
[10, 'Charlie', 'Physics', 88, 333]
[10, 'Charlie', 'History', 85, 333]
[10, 'Charlie', 'English', 82, 333]
[10, 'Charlie', 'Total Daily Performance', '', 333]
[10, 'David', 'Mathematics', 89, 349]
[10, 'David', 'Physics', 84, 349]
[10, 'David', 'History', 90, 349]
[10, 'David', 'English', 86, 349]
[10, 'David', 'Total Daily Performance', '', 349]
[11, 'Alice', 'Mathematics', 85, 341]
[11, 'Alice', 'Physics', 90, 341]
[11, 'Alice', 'History', 78, 341]
[11, 'Alice', 'English', 88, 341]
[11, 'Alice', 'Total Daily Performance', '', 341]
[11, 'Bob', 'Mathematics', 92, 347]
[11, 'Bob', 'Physics', 85, 347]
[11, 'Bob', 'History', 80, 347]
[11, 'Bob', 'English', 90, 347]
[11, 'Bob', 'Total Daily Performance', '', 347]
[11, 'Charlie', 'Mathematics', 78, 333]
[11, 'Charlie', 'Physics', 88, 333]
[11, 'Charlie', 'History', 85, 333]
[11, 'Charlie', 'English', 82, 333]
[11, 'Charlie', 'Total Daily Performance', '', 333]
[11, 'David', 'Mathematics', 89, 349]
[11, 'David', 'Physics', 84, 349]
[11, 'David', 'History', 90, 349]
[11, 'David', 'English', 86, 349]
[11, 'David', 'Total Daily Performance', '', 349]
[12, 'Alice', 'Mathematics', 85, 341]
[12, 'Alice', 'Physics', 90, 341]
[12, 'Alice', 'History', 78, 341]
[12, 'Alice', 'English', 88, 341]
[12, 'Alice', 'Total Daily Performance', '', 341]
[12, 'Bob', 'Mathematics', 92, 347]
[12, 'Bob', 'Physics', 85, 347]
[12, 'Bob', 'History', 80, 347]
[12, 'Bob', 'English', 90, 347]
[12, 'Bob', 'Total Daily Performance', '', 347]
[12, 'Charlie', 'Mathematics', 78, 333]
[12, 'Charlie', 'Physics', 88, 333]
[12, 'Charlie', 'History', 85, 333]
[12, 'Charlie', 'English', 82, 333]
[12, 'Charlie', 'Total Daily Performance', '', 333]
[12, 'David', 'Mathematics', 89, 349]
[12, 'David', 'Physics', 84, 349]
[12, 'David', 'History', 90, 349]
[12, 'David', 'English', 86, 349]
[12, 'David', 'Total Daily Performance', '', 349]
[13, 'Alice', 'Mathematics', 85, 341]
[13, 'Alice', 'Physics', 90, 341]
[13, 'Alice', 'History', 78, 341]
[13, 'Alice', 'English', 88, 341]
[13, 'Alice', 'Total Daily Performance', '', 341]
[13, 'Bob', 'Mathematics', 92, 347]
[13, 'Bob', 'Physics', 85, 347]
[13, 'Bob', 'History', 80, 347]
[13, 'Bob', 'English', 90, 347]
[13, 'Bob', 'Total Daily Performance', '', 347]
[13, 'Charlie', 'Mathematics', 78, 333]
[13, 'Charlie', 'Physics', 88, 333]
[13, 'Charlie', 'History', 85, 333]
[13, 'Charlie', 'English', 82, 333]
[13, 'Charlie', 'Total Daily Performance', '', 333]
[13, 'David', 'Mathematics', 89, 349]
[13, 'David', 'Physics', 84, 349]
[13, 'David', 'History', 90, 349]
[13, 'David', 'English', 86, 349]
[13, 'David', 'Total Daily Performance', '', 349]
[14, 'Alice', 'Mathematics', 85, 341]
[14, 'Alice', 'Physics', 90, 341]
[14, 'Alice', 'History', 78, 341]
[14, 'Alice', 'English', 88, 341]
[14, 'Alice', 'Total Daily Performance', '', 341]
[14, 'Bob', 'Mathematics', 92, 347]
[14, 'Bob', 'Physics', 85, 347]
[14, 'Bob', 'History', 80, 347]
[14, 'Bob', 'English', 90, 347]
[14, 'Bob', 'Total Daily Performance', '', 347]
[14, 'Charlie', 'Mathematics', 78, 333]
[14, 'Charlie', 'Physics', 88, 333]
[14, 'Charlie', 'History', 85, 333]
[14, 'Charlie', 'English', 82, 333]
[14, 'Charlie', 'Total Daily Performance', '', 333]
[14, 'David', 'Mathematics', 89, 349]
[14, 'David', 'Physics', 84, 349]
[14, 'David', 'History', 90, 349]
[14, 'David', 'English', 86, 349]
[14, 'David', 'Total Daily Performance', '', 349]
[15, 'Alice', 'Mathematics', 85, 341]
[15, 'Alice', 'Physics', 90, 341]
[15, 'Alice', 'History', 78, 341]
[15, 'Alice', 'English', 88, 341]
[15, 'Alice', 'Total Daily Performance', '', 341]
[15, 'Bob', 'Mathematics', 92, 347]
[15, 'Bob', 'Physics', 85, 347]
[15, 'Bob', 'History', 80, 347]
[15, 'Bob', 'English', 90, 347]
[15, 'Bob', 'Total Daily Performance', '', 347]
[15, 'Charlie', 'Mathematics', 78, 333]
[15, 'Charlie', 'Physics', 88, 333]
[15, 'Charlie', 'History', 85, 333]
[15, 'Charlie', 'English', 82, 333]
[15, 'Charlie', 'Total Daily Performance', '', 333]
[15, 'David', 'Mathematics', 89, 349]
[15, 'David', 'Physics', 84, 349]
[15, 'David', 'History', 90, 349]
[15, 'David', 'English', 86, 349]
[15, 'David', 'Total Daily Performance', '', 349]
[16, 'Alice', 'Mathematics', 85, 341]
[16, 'Alice', 'Physics', 90, 341]
[16, 'Alice', 'History', 78, 341]
[16, 'Alice', 'English', 88, 341]
[16, 'Alice', 'Total Daily Performance', '', 341]
[16, 'Bob', 'Mathematics', 92, 347]
[16, 'Bob', 'Physics', 85, 347]
[16, 'Bob', 'History', 80, 347]
[16, 'Bob', 'English', 90, 347]
[16, 'Bob', 'Total Daily Performance', '', 347]
[16, 'Charlie', 'Mathematics', 78, 333]
[16, 'Charlie', 'Physics', 88, 333]
[16, 'Charlie', 'History', 85, 333]
[16, 'Charlie', 'English', 82, 333]
[16, 'Charlie', 'Total Daily Performance', '', 333]
[16, 'David', 'Mathematics', 89, 349]
[16, 'David', 'Physics', 84, 349]
[16, 'David', 'History', 90, 349]
[16, 'David', 'English', 86, 349]
[16, 'David', 'Total Daily Performance', '', 349]
[17, 'Alice', 'Mathematics', 85, 341]
[17, 'Alice', 'Physics', 90, 341]
[17, 'Alice', 'History', 78, 341]
[17, 'Alice', 'English', 88, 341]
[17, 'Alice', 'Total Daily Performance', '', 341]
[17, 'Bob', 'Mathematics', 92, 347]
[17, 'Bob', 'Physics', 85, 347]
[17, 'Bob', 'History', 80, 347]
[17, 'Bob', 'English', 90, 347]
[17, 'Bob', 'Total Daily Performance', '', 347]
[17, 'Charlie', 'Mathematics', 78, 333]
[17, 'Charlie', 'Physics', 88, 333]
[17, 'Charlie', 'History', 85, 333]
[17, 'Charlie', 'English', 82, 333]
[17, 'Charlie', 'Total Daily Performance', '', 333]
[17, 'David', 'Mathematics', 89, 349]
[17, 'David', 'Physics', 84, 349]
[17, 'David', 'History', 90, 349]
[17, 'David', 'English', 86, 349]
[17, 'David', 'Total Daily Performance', '', 349]
[18, 'Alice', 'Mathematics', 85, 341]
[18, 'Alice', 'Physics', 90, 341]
[18, 'Alice', 'History', 78, 341]
[18, 'Alice', 'English', 88, 341]
[18, 'Alice', 'Total Daily Performance', '', 341]
[18, 'Bob', 'Mathematics', 92, 347]
[18, 'Bob', 'Physics', 85, 347]
[18, 'Bob', 'History', 80, 347]
[18, 'Bob', 'English', 90, 347]
[18, 'Bob', 'Total Daily Performance', '', 347]
[18, 'Charlie', 'Mathematics', 78, 333]
[18, 'Charlie', 'Physics', 88, 333]
[18, 'Charlie', 'History', 85, 333]
[18, 'Charlie', 'English', 82, 333]
[18, 'Charlie', 'Total Daily Performance', '', 333]
[18, 'David', 'Mathematics', 89, 349]
[18, 'David', 'Physics', 84, 349]
[18, 'David', 'History', 90, 349]
[18, 'David', 'English', 86, 349]
[18, 'David', 'Total Daily Performance', '', 349]
[19, 'Alice', 'Mathematics', 85, 341]
[19, 'Alice', 'Physics', 90, 341]
[19, 'Alice', 'History', 78, 341]
[19, 'Alice', 'English', 88, 341]
[19, 'Alice', 'Total Daily Performance', '', 341]
[19, 'Bob', 'Mathematics', 92, 347]
[19, 'Bob', 'Physics', 85, 347]
[19, 'Bob', 'History', 80, 347]
[19, 'Bob', 'English', 90, 347]
[19, 'Bob', 'Total Daily Performance', '', 347]
[19, 'Charlie', 'Mathematics', 78, 333]
[19, 'Charlie', 'Physics', 88, 333]
[19, 'Charlie', 'History', 85, 333]
[19, 'Charlie', 'English', 82, 333]
[19, 'Charlie', 'Total Daily Performance', '', 333]
[19, 'David', 'Mathematics', 89, 349]
[19, 'David', 'Physics', 84, 349]
[19, 'David', 'History', 90, 349]
[19, 'David', 'English', 86, 349]
[19, 'David', 'Total Daily Performance', '', 349]
[20, 'Alice', 'Mathematics', 85, 341]
[20, 'Alice', 'Physics', 90, 341]
[20, 'Alice', 'History', 78, 341]
[20, 'Alice', 'English', 88, 341]
[20, 'Alice', 'Total Daily Performance', '', 341]
[20, 'Bob', 'Mathematics', 92, 347]
[20, 'Bob', 'Physics', 85, 347]
[20, 'Bob', 'History', 80, 347]
[20, 'Bob', 'English', 90, 347]
[20, 'Bob', 'Total Daily Performance', '', 347]
[20, 'Charlie', 'Mathematics', 78, 333]
[20, 'Charlie', 'Physics', 88, 333]
[20, 'Charlie', 'History', 85, 333]
[20, 'Charlie', 'English', 82, 333]
[20, 'Charlie', 'Total Daily Performance', '', 333]
[20, 'David', 'Mathematics', 89, 349]
[20, 'David', 'Physics', 84, 349]
[20, 'David', 'History', 90, 349]
[20, 'David', 'English', 86, 349]
[20, 'David', 'Total Daily Performance', '', 349]
[21, 'Alice', 'Mathematics', 85, 341]
[21, 'Alice', 'Physics', 90, 341]
[21, 'Alice', 'History', 78, 341]
[21, 'Alice', 'English', 88, 341]
[21, 'Alice', 'Total Daily Performance', '', 341]
[21, 'Bob', 'Mathematics', 92, 347]
[21, 'Bob', 'Physics', 85, 347]
[21, 'Bob', 'History', 80, 347]
[21, 'Bob', 'English', 90, 347]
[21, 'Bob', 'Total Daily Performance', '', 347]
[21, 'Charlie', 'Mathematics', 78, 333]
[21, 'Charlie', 'Physics', 88, 333]
[21, 'Charlie', 'History', 85, 333]
[21, 'Charlie', 'English', 82, 333]
[21, 'Charlie', 'Total Daily Performance', '', 333]
[21, 'David', 'Mathematics', 89, 349]
[21, 'David', 'Physics', 84, 349]
[21, 'David', 'History', 90, 349]
[21, 'David', 'English', 86, 349]
[21, 'David', 'Total Daily Performance', '', 349]
[22, 'Alice', 'Mathematics', 85, 341]
[22, 'Alice', 'Physics', 90, 341]
[22, 'Alice', 'History', 78, 341]
[22, 'Alice', 'English', 88, 341]
[22, 'Alice', 'Total Daily Performance', '', 341]
[22, 'Bob', 'Mathematics', 92, 347]
[22, 'Bob', 'Physics', 85, 347]
[22, 'Bob', 'History', 80, 347]
[22, 'Bob', 'English', 90, 347]
[22, 'Bob', 'Total Daily Performance', '', 347]
[22, 'Charlie', 'Mathematics', 78, 333]
[22, 'Charlie', 'Physics', 88, 333]
[22, 'Charlie', 'History', 85, 333]
[22, 'Charlie', 'English', 82, 333]
[22, 'Charlie', 'Total Daily Performance', '', 333]
[22, 'David', 'Mathematics', 89, 349]
[22, 'David', 'Physics', 84, 349]
[22, 'David', 'History', 90, 349]
[22, 'David', 'English', 86, 349]
[22, 'David', 'Total Daily Performance', '', 349]
[23, 'Alice', 'Mathematics', 85, 341]
[23, 'Alice', 'Physics', 90, 341]
[23, 'Alice', 'History', 78, 341]
[23, 'Alice', 'English', 88, 341]
[23, 'Alice', 'Total Daily Performance', '', 341]
[23, 'Bob', 'Mathematics', 92, 347]
[23, 'Bob', 'Physics', 85, 347]
[23, 'Bob', 'History', 80, 347]
[23, 'Bob', 'English', 90, 347]
[23, 'Bob', 'Total Daily Performance', '', 347]
[23, 'Charlie', 'Mathematics', 78, 333]
[23, 'Charlie', 'Physics', 88, 333]
[23, 'Charlie', 'History', 85, 333]
[23, 'Charlie', 'English', 82, 333]
[23, 'Charlie', 'Total Daily Performance', '', 333]
[23, 'David', 'Mathematics', 89, 349]
[23, 'David', 'Physics', 84, 349]
[23, 'David', 'History', 90, 349]
[23, 'David', 'English', 86, 349]
[23, 'David', 'Total Daily Performance', '', 349]
[24, 'Alice', 'Mathematics', 85, 341]
[24, 'Alice', 'Physics', 90, 341]
[24, 'Alice', 'History', 78, 341]
[24, 'Alice', 'English', 88, 341]
[24, 'Alice', 'Total Daily Performance', '', 341]
[24, 'Bob', 'Mathematics', 92, 347]
[24, 'Bob', 'Physics', 85, 347]
[24, 'Bob', 'History', 80, 347]
[24, 'Bob', 'English', 90, 347]
[24, 'Bob', 'Total Daily Performance', '', 347]
[24, 'Charlie', 'Mathematics', 78, 333]
[24, 'Charlie', 'Physics', 88, 333]
[24, 'Charlie', 'History', 85, 333]
[24, 'Charlie', 'English', 82, 333]
[24, 'Charlie', 'Total Daily Performance', '', 333]
[24, 'David', 'Mathematics', 89, 349]
[24, 'David', 'Physics', 84, 349]
[24, 'David', 'History', 90, 349]
[24, 'David', 'English', 86, 349]
[24, 'David', 'Total Daily Performance', '', 349]
[25, 'Alice', 'Mathematics', 85, 341]
[25, 'Alice', 'Physics', 90, 341]
[25, 'Alice', 'History', 78, 341]
[25, 'Alice', 'English', 88, 341]
[25, 'Alice', 'Total Daily Performance', '', 341]
[25, 'Bob', 'Mathematics', 92, 347]
[25, 'Bob', 'Physics', 85, 347]
[25, 'Bob', 'History', 80, 347]
[25, 'Bob', 'English', 90, 347]
[25, 'Bob', 'Total Daily Performance', '', 347]
[25, 'Charlie', 'Mathematics', 78, 333]
[25, 'Charlie', 'Physics', 88, 333]
[25, 'Charlie', 'History', 85, 333]
[25, 'Charlie', 'English', 82, 333]
[25, 'Charlie', 'Total Daily Performance', '', 333]
[25, 'David', 'Mathematics', 89, 349]
[25, 'David', 'Physics', 84, 349]
[25, 'David', 'History', 90, 349]
[25, 'David', 'English', 86, 349]
[25, 'David', 'Total Daily Performance', '', 349]
[26, 'Alice', 'Mathematics', 85, 341]
[26, 'Alice', 'Physics', 90, 341]
[26, 'Alice', 'History', 78, 341]
[26, 'Alice', 'English', 88, 341]
[26, 'Alice', 'Total Daily Performance', '', 341]
[26, 'Bob', 'Mathematics', 92, 347]
[26, 'Bob', 'Physics', 85, 347]
[26, 'Bob', 'History', 80, 347]
[26, 'Bob', 'English', 90, 347]
[26, 'Bob', 'Total Daily Performance', '', 347]
[26, 'Charlie', 'Mathematics', 78, 333]
[26, 'Charlie', 'Physics', 88, 333]
[26, 'Charlie', 'History', 85, 333]
[26, 'Charlie', 'English', 82, 333]
[26, 'Charlie', 'Total Daily Performance', '', 333]
[26, 'David', 'Mathematics', 89, 349]
[26, 'David', 'Physics', 84, 349]
[26, 'David', 'History', 90, 349]
[26, 'David', 'English', 86, 349]
[26, 'David', 'Total Daily Performance', '', 349]
[27, 'Alice', 'Mathematics', 85, 341]
[27, 'Alice', 'Physics', 90, 341]
[27, 'Alice', 'History', 78, 341]
[27, 'Alice', 'English', 88, 341]
[27, 'Alice', 'Total Daily Performance', '', 341]
[27, 'Bob', 'Mathematics', 92, 347]
[27, 'Bob', 'Physics', 85, 347]
[27, 'Bob', 'History', 80, 347]
[27, 'Bob', 'English', 90, 347]

In [21]:
columns = ["Day", "Person", "Subject", "Subject Score", "Total Daily Performance"]

# Create the DataFrame
df = pd.DataFrame(performance_data, columns=columns)

In [22]:
df

,Day,Person,Subject,Subject Score,Total Daily Performance
0,1,Alice,Mathematics,85,341
1,1,Alice,Physics,90,341
2,1,Alice,History,78,341
3,1,Alice,English,88,341
4,1,Alice,Total Daily Performance,,341
...,...,...,...,...,...
595,30,David,Mathematics,89,349
596,30,David,Physics,84,349
597,30,David,History,90,349
598,30,David,English,86,349
599,30,David,Total Daily Performance,,349

In [28]:
day_performance = df[df['Subject'] == 'Total Daily Performance']

In [29]:
day_performance

,Day,Person,Subject,Subject Score,Total Daily Performance
4,1,Alice,Total Daily Performance,,341
9,1,Bob,Total Daily Performance,,347
14,1,Charlie,Total Daily Performance,,333
19,1,David,Total Daily Performance,,349
24,2,Alice,Total Daily Performance,,341
...,...,...,...,...,...
579,29,David,Total Daily Performance,,349
584,30,Alice,Total Daily Performance,,341
589,30,Bob,Total Daily Performance,,347
594,30,Charlie,Total Daily Performance,,333
599,30,David,Total Daily Performance,,349

In [33]:
import plotly.express as px

# Filter the rows where Subject is "Total Daily Performance"
day_performance = df[df['Subject'] == 'Total Daily Performance']

# Create a Plotly line chart for total daily performance
fig = px.line(day_performance,
              x="Day",
              y="Total Daily Performance",  # Change y to "Total Daily Performance"
              title="Total Daily Performance Over Time",
              labels={
                  "Day": "Day of the Month",
                  "Total Daily Performance": "Total Performance"
              })

# Show the plot
fig.show()

In [34]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [35]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/13dE1hwIBE9Dpto5eL_JTpRwElPyeKEMu6t5bGdTiaok/edit?usp=sharing')

In [36]:
from gspread_dataframe import set_with_dataframe

# 選擇要更新的工作表（選擇第一個工作表）
worksheet = gsheets.get_worksheet(0)  # 如果是其他工作表，可以用 get_worksheet(index)

# 將 DataFrame 寫入 Google Sheets
set_with_dataframe(worksheet, df)